export const DEFAULT_LABELS = [
  { column_type: 'who', value: 'Wenneker', color: '#28b8ff', is_default: true },
  { column_type: 'who', value: 'Client', color: '#ffcf5c', is_default: true },
  { column_type: 'who', value: 'Agency', color: '#8d79ff', is_default: true },
  { column_type: 'what', value: 'Offline V1', color: '#ffd166', is_default: true },
  { column_type: 'what', value: 'Offline V2', color: '#f0a83a', is_default: true },
  { column_type: 'what', value: 'Offline Lock', color: '#b793ff', is_default: true },
  { column_type: 'what', value: 'Prefinal V1', color: '#54c7ff', is_default: true },
  { column_type: 'what', value: 'Prefinal V2', color: '#4aa3ff', is_default: true },
  { column_type: 'what', value: 'Final', color: '#ff5e84', is_default: true },
  { column_type: 'what', value: 'Final Delivery', color: '#ff8f4f', is_default: true },
  { column_type: 'what', value: 'Grading', color: '#31d0aa', is_default: true },
  { column_type: 'what', value: 'Audio', color: '#9ee66b', is_default: true },
  { column_type: 'todo', value: 'Offline V1', color: '#ffd166', is_default: true },
  { column_type: 'todo', value: 'Offline V2', color: '#ffd166', is_default: true },
  { column_type: 'todo', value: 'Offline V3', color: '#ffd166', is_default: true },
  { column_type: 'todo', value: 'Offline Final', color: '#ffd166', is_default: true },
  { column_type: 'todo', value: 'Offline Lock', color: '#b793ff', is_default: true },
  { column_type: 'todo', value: 'PreFinal', color: '#54c7ff', is_default: true },
  { column_type: 'todo', value: 'PreFinal V1', color: '#54c7ff', is_default: true },
  { column_type: 'todo', value: 'PreFinal V2', color: '#54c7ff', is_default: true },
  { column_type: 'todo', value: 'Final', color: '#ff5e84', is_default: true },
  { column_type: 'todo', value: 'Final Delivery', color: '#46d39b', is_default: true },
  { column_type: 'todo', value: 'Grading', color: '#8b8f9a', is_default: true },
  { column_type: 'todo', value: 'Audio', color: '#8b8f9a', is_default: true },
  { column_type: 'todo', value: '360 V1', color: '#9a6a43', is_default: true },
  { column_type: 'todo', value: '360 V2', color: '#9a6a43', is_default: true },
  { column_type: 'todo', value: 'CGI WIP V1', color: '#ff8f4f', is_default: true },
  { column_type: 'todo', value: 'CGI WIP V2', color: '#ff8f4f', is_default: true },
  { column_type: 'todo', value: 'CGI WIP V3', color: '#ff8f4f', is_default: true },
  { column_type: 'todo', value: 'CGI Lock', color: '#b793ff', is_default: true },
  { column_type: 'todo', value: 'DesignV1', color: '#f45fd2', is_default: true },
  { column_type: 'todo', value: 'Design V2', color: '#f45fd2', is_default: true },
  { column_type: 'todo', value: 'Design V3', color: '#f45fd2', is_default: true },
  { column_type: 'todo', value: 'Photography V1', color: '#ffd166', is_default: true },
  { column_type: 'todo', value: 'Photography V2', color: '#ffd166', is_default: true },
  { column_type: 'todo', value: 'Creative V1', color: '#b793ff', is_default: true },
  { column_type: 'todo', value: 'Creative V2', color: '#b793ff', is_default: true },
  { column_type: 'todo', value: 'CAD/MUS/PGD', color: '#8b8f9a', is_default: true },
  { column_type: 'todo', value: 'CIMA', color: '#8b8f9a', is_default: true },
  { column_type: 'todo', value: 'Shoot', color: '#8b8f9a', is_default: true },
];

export const DEFAULT_PROJECT = {
  name: 'Timeline Planning',
  client: 'Demo client',
};
