export const DEFAULT_LABELS = [
  { column_type: 'who', value: 'Wenneker', color: '#37B6FF', is_default: true },
  { column_type: 'who', value: 'Client', color: '#F5D900', is_default: true },
  { column_type: 'who', value: 'Agency', color: '#B9A4FF', is_default: true },
  { column_type: 'what', value: 'Offline V1', color: '#F5D900', is_default: true },
  { column_type: 'what', value: 'Offline V2', color: '#F5D900', is_default: true },
  { column_type: 'what', value: 'Offline V3', color: '#F5D900', is_default: true },
  { column_type: 'what', value: 'Offline Final', color: '#F5D900', is_default: true },
  { column_type: 'what', value: 'Offline Lock', color: '#B9A4FF', is_default: true },
  { column_type: 'what', value: 'PreFinal', color: '#A7D4FF', is_default: true },
  { column_type: 'what', value: 'PreFinal V1', color: '#A7D4FF', is_default: true },
  { column_type: 'what', value: 'PreFinal V2', color: '#A7D4FF', is_default: true },
  { column_type: 'what', value: 'Final', color: '#FF6F91', is_default: true },
  { column_type: 'what', value: 'Final Delivery', color: '#8FE5A1', is_default: true },
  { column_type: 'what', value: 'Grading', color: '#D8D8D0', is_default: true },
  { column_type: 'what', value: 'Audio', color: '#D8D8D0', is_default: true },
  { column_type: 'what', value: '360 V1', color: '#C28A56', is_default: true },
  { column_type: 'what', value: '360 V2', color: '#C28A56', is_default: true },
  { column_type: 'what', value: 'CGI WIP V1', color: '#FF9B42', is_default: true },
  { column_type: 'what', value: 'CGI WIP V2', color: '#FF9B42', is_default: true },
  { column_type: 'what', value: 'CGI WIP V3', color: '#FF9B42', is_default: true },
  { column_type: 'what', value: 'CGI Lock', color: '#B9A4FF', is_default: true },
  { column_type: 'what', value: 'DesignV1', color: '#FF9CCC', is_default: true },
  { column_type: 'what', value: 'Design V2', color: '#FF9CCC', is_default: true },
  { column_type: 'what', value: 'Design V3', color: '#FF9CCC', is_default: true },
  { column_type: 'what', value: 'Photography V1', color: '#F5D900', is_default: true },
  { column_type: 'what', value: 'Photography V2', color: '#F5D900', is_default: true },
  { column_type: 'what', value: 'Creative V1', color: '#B9A4FF', is_default: true },
  { column_type: 'what', value: 'Creative V2', color: '#B9A4FF', is_default: true },
  { column_type: 'what', value: 'CAD/MUS/PGD', color: '#D8D8D0', is_default: true },
  { column_type: 'what', value: 'CIMA', color: '#D8D8D0', is_default: true },
  { column_type: 'what', value: 'Shoot', color: '#D8D8D0', is_default: true },
  { column_type: 'todo', value: 'Share', color: '#8FE5A1', is_default: true },
  { column_type: 'todo', value: 'Viewing at Wenneker', color: '#8FE5A1', is_default: true },
  { column_type: 'todo', value: 'Session at Wenneker', color: '#8FE5A1', is_default: true },
  { column_type: 'todo', value: 'Viewing online', color: '#8FE5A1', is_default: true },
  { column_type: 'todo', value: 'Share Feedback', color: '#A7D4FF', is_default: true },
  { column_type: 'todo', value: 'Approval', color: '#B9A4FF', is_default: true },
  { column_type: 'todo', value: 'Internal', color: '#D8D8D0', is_default: true },
  { column_type: 'todo', value: 'Upload PAL & EG+', color: '#FF6F91', is_default: true },
  { column_type: 'todo', value: 'Upload DAM', color: '#FF6F91', is_default: true },
  { column_type: 'todo', value: 'Upload SAL', color: '#FF6F91', is_default: true },
];

export const DEFAULT_PROJECT = {
  name: 'Timeline Planning',
  client: 'Demo client',
};

export const DEFAULT_PLANNING_WHAT_LABELS = [
  'Offline V1',
  'Offline V2',
  'Offline Final',
  'PreFinal V1',
  'PreFinal V2',
  'Final',
  'Final Delivery',
];

export const DEFAULT_PLANNING_ALIASES = {
  finals: ['finals', 'final'],
};
